name: Build Preview

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
      - run: npm clean-install
      - run: npm run dist
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: openstreetmap/iD
          path: './iD'
      - run: npm clean-install
        working-directory: './iD'
      - run: npm run all
        working-directory: './iD'
        env:
          ID_PRESETS_CDN_URL: '../../'
      - run: npm run dist
        working-directory: './iD'
        env:
          ID_PRESETS_CDN_URL: '../../'

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: preview
          path: |
            dist
            iD/dist

      - name: Store pull request number for later use
        run: |
          echo ${{github.event.number}} > ./pr_number
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: pr
          path: ./pr_number
